name: main


on: push


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-node@v2
        with:
          node-version: '16'
      - name: make-setup
        run: make setup
      - name: make-test
        run: make test
      - name: make-lint
        run: make lint
